[package]
name = "params"
version = "0.0.2"
authors = ["Skyler Lipthay <skyler.lipthay@gmail.com>"]
description = "A multi-source request parameters parser for Iron."
readme = "README.md"
license = "MIT"
repository = "https://github.com/iron/params"
documentation = "http://ironframework.io/doc/params/index.html"

[dependencies]
bodyparser = "0.2.0"
formdata = "=0.7.9"
iron = "0.2.6"
num = "0.1.31"
plugin = "0.2.6"
rustc-serialize = "0.3.18"
urlencoded = "0.2.1"
